/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*/


//Hashmap approach
class Solution {
public:
    char findTheDifference(string s, string t) {
        vector<int> phash(26,0);
        for(int i =0;i<s.size();i++){
            phash[(int)s[i]-97]++;
        }
        vector<int> chash(26,0);
        for(int i =0;i<t.size();i++){
            chash[(int)t[i]-97]++;
        }
        for(int i = 0;i<26;i++){
            if(phash[i]!=chash[i]){
                char ch = i+97;
                return ch;
            }
        }
        return '-1';
    }
};
//Bit manipulation approach
class Solution {
public:
    char findTheDifference(string s, string t) {
        int ans = 0;
        for(int i =0;i<s.size();i++) ans^=s[i];
        for(int i =0;i<t.size();i++) ans^=t[i];
        return ans;
    }
};
